### ISSUE TITLE
Add Bower Support

### ISSUE THREAD

**Issue by alanjames1987** [chocolatechipui/chocolatechip-ui#33]
I know ChocolateChip-UI is availible through NPM but it would be great to have it also availible through Bower.

I will add this and create a pull request if this is desired.

**Comment by chocolatechipui** [comment]
Actually, we'll looking to this. I think it's just a matter of adding a bower.json file to the repository. Busy with other issues for the next few days, so hold on.

**Comment by alanjames1987** [comment]
Will do. Thanks for the update.

**Comment by chocolatechipui** [comment]
For anyone wanting Bower, we do have a very good NPM module: https://www.npmjs.com/package/chui
Install and create basic projects from command line.
