### ISSUE TITLE
CSS version 3.8.2 not working

### ISSUE THREAD

**Issue by anggietp** [chocolatechipui/chocolatechip-ui#9]
I've been wondering why class "back button" (on android and iOS) not showing properly (text only, no arrow) when I use CSS version 3.8.2. BUT It working great when I use version 3.0.4. 

I didn't modify anything, only version number.
Why?

**Comment by mmbabel** [comment]
In 3.8 you need to take <button class="back">Back</button> in opposite to 3.0 where you had <a class="button back">

But there is another issue,
problem is the minified version are missing in the mask image sag's the ' signs. if you take the non minified version everything is fine. Think they get accidentally stripped out during minifying.

**Comment by chocolatechipui** [comment]
This has been resolved.
